In [21]:
import pandas as pd
from datasets import load_dataset

pd.set_option('display.max_colwidth', None)

# Load the dataset from the hub
dataset = load_dataset("ChanceFocus/fiqa-sentiment-classification")

# Convert splits into dataframes
train_df = pd.DataFrame(dataset['train'])
validation_df = pd.DataFrame(dataset['valid'])
test_df = pd.DataFrame(dataset['test'])

# Concatenate the dataframes
df = pd.concat([train_df, validation_df, test_df], ignore_index=True)

# Display dataframe information
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1173 entries, 0 to 1172
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   _id       1173 non-null   object
 1   sentence  1173 non-null   object
 2   target    1173 non-null   object
 3   aspect    1173 non-null   object
 4   score     1173 non-null   float64
 5   type      1173 non-null   object
dtypes: float64(1), object(5)
memory usage: 55.1+ KB

None

In [23]:
# add column sentiment to the df where sentiment is over 1.3 if the label is positive and under -0.33 if the label is negative else neutral
df['sentiment'] = df['score'].apply(lambda x: 'positive' if x > 0.3333 else ('negative' if x < -0.33333 else 'neutral'))

# rename sentence to text
df.rename(columns={'sentence': 'text'}, inplace=True)

In [29]:
# Filter rows based on the length of the text
filtered_df = df[(df['text'].str.len() > 45) & (df['text'].str.len() < 51)]
# display(filtered_df[['text', 'sentiment']])

# Helper function to safely sample and display rows
def safe_sample_display(df, n_samples, sentiment):
    if len(df) < n_samples:
        print(f"Not enough samples for {sentiment} sentiment")
    else:
        display(df.sample(n=n_samples))

# Display samples or a message if there are not enough samples
safe_sample_display(filtered_df[filtered_df['sentiment'] == 'positive'], 3, 'positive')
safe_sample_display(filtered_df[filtered_df['sentiment'] == 'neutral'], 3, 'neutral')
safe_sample_display(filtered_df[filtered_df['sentiment'] == 'negative'], 3, 'negative')

,_id,text,target,aspect,score,type,sentiment
931,17952,Added long at friday close $SPY $LABU $BLUE $AMZN,SPY,Stock/Price Action/Bullish/Bull Position,0.513,post,positive
133,1412,Britain's FTSE gets lift from Prudential results,Prudential,Corporate/Financial,0.582,headline,positive
425,15176,$HITK Resuming advance into new historical highs.,HITK,Stock/Price Action/Current Price/52-Week High,0.680,post,positive

,_id,text,target,aspect,score,type,sentiment
104,1334,MarketsBP promotes upstream boss to deputy CEO,BP,Corporate/Appointment,0.066,headline,neutral
352,14875,$GRPN might be selling off ahead of $P earnings...,P,Stock/Price Action/Bearish/Bearish Behavior,-0.202,post,neutral
996,861,AB InBev looks to win over SABMiller investors,SABMiller,Corporate/M&A/Proposed Merger,0.276,headline,neutral

,_id,text,target,aspect,score,type,sentiment
1,100,Slump in Weir leads FTSE down from record high,Weir,Market/Volatility/Volatility,-0.827,headline,negative
306,381,AstraZeneca profit down as sales of stalwarts fade,AstraZeneca,Corporate/Sales,-0.405,headline,negative
0,1,Royal Mail chairman Donald Brydon set to step down,Royal Mail,Corporate/Appointment,-0.374,headline,negative